[package]
name = "ngram_dedup"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
indicatif = { version = "0.17.8", features = ["rayon", "improved_unicode"] }
rayon = "1.10.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
